#!/bin/bash
#
# Download and deploy WordPress and all listed themes/plugins
#

usage() { echo "Usage: $0 [-c <string>]" 1>&2; exit 1; }

while getopts ":c:" o; do
    case "${o}" in
        c)
            c=${OPTARG}
            [ -f $c ] || usage
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))
if [ -z "${c}" ]; then
    usage
fi

# Import config variables
echo "Sourcing config file '$c'..."
. $c

# Needs certain environment variables set
if [ "x$WP_THEMES_LIST" = "x" ]; then
    echo "Need to set WP_THEMES_LIST."
    exit 1
fi
if [ "x$WP_PLUGIN_LIST" = "x" ]; then
    echo "Need to set WP_PLUGIN_LIST."
    exit 1
fi

# Ensure we know where to get WP base from
if [ "x$WP_DOWNLOAD_URL" = "x" ]; then
    WP_DOWNLOAD_URL="http://wordpress.org/latest.zip"
fi

# Determine where to place the resulting ZIP file
packedzipfile=$(pwd)/wordpress-prepacked.zip

# Create a working directory to build this all in
tmpdir=`mktemp -d` && cd $tmpdir

# Grab WordPress and install it first
echo "Installing WordPress base"
curl -OLs $WP_DOWNLOAD_URL
if [ $? != 0 ]; then
    echo "Failed to download WordPress zip."
    exit 1
fi
unzip -qo `basename $WP_DOWNLOAD_URL`
if [ $? != 0 ]; then
    echo "Failed to unzip WordPress zip."
    exit 1
fi

# Clear out the existing plugins/themes
rm -rf wordpress/wp-content/plugins/*
rm -rf wordpress/wp-content/themes/*

# Grab a copy of each theme and deploy it
for i in $WP_THEMES_LIST; do
    zipfile=`basename $i`
    echo "Installing theme $zipfile"
    cd $tmpdir
    curl -OLs $i
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to fetch $i"
        exit 1;
    fi
    tmpsubdir=`mktemp -d` && cd $tmpsubdir
    unzip -qo $tmpdir/$zipfile
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to unzip $zipfile"
        exit 1;
    fi
    themedir=`ls -1`
    mv $themedir $tmpdir/wordpress/wp-content/themes
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to move $themedir into place."
        exit 1;
    fi
    cd $tmpdir
    rm -rf $tmpsubdir
done

# Grab a copy of each plugin and deploy it
for i in $WP_PLUGIN_LIST; do
    zipfile=`basename $i`
    echo "Installing plugin $zipfile"
    curl -OLs $i
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to fetch $i"
        exit 1;
    fi
    tmpsubdir=`mktemp -d` && cd $tmpsubdir
    unzip -qo $tmpdir/$zipfile
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to unzip $zipfile"
        exit 1;
    fi
    plugindir=`ls -1`
    mv $plugindir $tmpdir/wordpress/wp-content/plugins
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to move $plugindir into place."
        exit 1;
    fi
    cd $tmpdir
    rm -rf $tmpsubdir
done

# Install configuration file
if [ "x$WP_CONFIG_FILE" != "x" ]; then
    echo "Putting config file in place."
    cp $WP_CONFIG_FILE wordpress/wp-config.php
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to move config file into place."
        exit 1;
    fi
fi

# Install htaccess file
if [ "x$WP_HTACCESS_FILE" != "x" ]; then
    echo "Putting htaccess file in place."
    cp $WP_HTACCESS_FILE wordpress/.htaccess
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to move htaccess into place."
        exit 1;
    fi
fi

# Install Beanstalk configuration (.ebextensions)
if [ "x$WP_BEANSTALK_CONFIG" != "x" ]; then
    echo "Putting Beanstalk config in place."
    cp -r $WP_BEANSTALK_CONFIG wordpress/.ebextensions
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to move ebextensions into place."
        exit 1;
    fi
fi

# Pop it all in one big zip file
echo "Packing up master zip file..."
(cd wordpress && zip -qr $packedzipfile .)
if [ $? -ne 0 ]; then
    echo "ERROR: Failed to zip up packed zip file."
    exit 1;
fi

# Clear down the temporary directory
echo "Clearing down temporary files."
rm -rf $tmpdir

echo "Done."

